### DISCUSSION TITLE
Feature Requests

### DISCUSSION THREAD

**Discussion by Schluggi** [Schluggi/AIOsense#22] [Ideas]
Is there anything you like to have in the future?

**Comment by Schluggi** [comment]
A [rtttl buzzer](https://esphome.io/components/rtttl.html) to make some noise.

**Reply by Schluggi** [reply]
I was not able to make sound with a RTTTL buzzer. Maybe because of this issue: https://github.com/esphome/issues/issues/3925

Update: Related to [this post](https://github.com/esphome/issues/issues/3925#issuecomment-1405761976) the RTTTL buzzer works just fine. Because its easy to implement this is something we could easily include in v2.1 later this year.

If you can't wait, here my config for the ESP32-C3:
```yaml
external_components:
  - source: github://pr#3564
    components: 
      - esp32
      - esp32_camera
      - ethernet_info
      - ethernet
      - shelly_dimmer
      - wifi
      - dallas

  - source: github://pr#3820
    components: [ ledc ]

api:
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
output:
  - platform: ledc
    pin: GPIO0
    id: rtttl_out

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'
```

Afterwards you have a new service in HA you can call: `play_rtttl`.

Example RTTTL-string:
`"mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16c7,16p,16c7,16c7,p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16d#6,8p,16d6,8p,16c6"`
