### DISCUSSION TITLE
Config upload issues...

### DISCUSSION THREAD

**Discussion by philfry9** [Schluggi/AIOsense#79] [Q&A] [answered]
Somewhat familiar with esp devices, but having some issues with getting this to work.
My setup that I built is esp32-s2-mini, bh1750, bme680, ld2410c, pir.

Config is:

```
substitutions:
  name: "aiosense-mastbath"  # lowercase only, have to be unique
  friendly_name: "AIOsense Master Bath"  # device name and entity prefix
  version: "2.0.0"  # your AIOsense version

  # bh1750_update_interval: 5s

  # bmex80_address: "0x76"  # for some modules you have to change it to 0x77
  # bmex80_offset_humidity: "0"
  # bmex80_offset_temperature: "0"
  # bmex80_update_interval: 30s

  bme680_bsec_sample_rate: lp # lp -> 3s, ulp ->5min
  bme680_bsec_temperature_offset: "0"

  # ld2410_max_distance_move: 4.5m
  # ld2410_max_distance_still: 4.5m
  # ld2410_timeout: 5s

  # pir_delayed_off: 1s
  # pir_delayed_on: 0s

packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: main
    refresh: 1d
    files:
      - esphome/packages/config/base.yaml

      # --- select your board ---
      # - esphome/packages/config/esp32-c3-mini.yaml
      # - esphome/packages/config/esp32-d1-mini.yaml
      - esphome/packages/config/esp32-s2-mini.yaml
      # - esphome/packages/config/esp8266-d1-mini.yaml

      # --- select your sensors ---
      - esphome/packages/sensors/bh1750.yaml
      # - esphome/packages/sensors/buzzer.yaml  # AIOsense >= 2.1.x only
      # - esphome/packages/sensors/bme280.yaml  # enable for bme280
      - esphome/packages/sensors/bme680.yaml  # disable for bme280
      # - esphome/packages/sensors/bme680_bsec.yaml  # does not work yet
      - esphome/packages/sensors/occupancy.yaml  # only if pir & mmWave are on
      - esphome/packages/sensors/pir.yaml
      # - esphome/packages/sensors/rgb_led.yaml  # esp32-c3-mini only
      # - esphome/packages/sensors/led.yaml  # d1-mini only

      # --- select your radar sensor ---
      - esphome/packages/sensors/ld2410.yaml
      # - esphome/packages/sensors/sen0395.yaml


# Enable Home Assistant API
api:
  encryption:
    key: "my key is here"

ota:
  password: "my key is here"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 192.168.1.111
  #   subnet: 255.255.255.0
  #   gateway: 192.168.1.1

# bluetooth_proxy:

```

Connecting to the esp from esphome to program fine. Was able to put a test on it without issue.
Error I am getting is:

```
INFO ESPHome 2023.5.5
INFO Reading configuration /config/esphome/aiosense.yaml...
Failed config

captive_portal: [source /config/esphome/.esphome/packages/f7a0b76d/esphome/packages/config/base.yaml:15]
  
  This feature is only available with frameworks ['arduino'].
  {}
async_tcp: None
  {}
This feature is only available with frameworks ['arduino']
```

Am I missing something simple? Appreciate the help.

**Comment by Schluggi** [comment]
Hi @philfry9, 

looks like we haven't tested the s2mini. I'll do it later this week and upload the fix.

No mistake on your side :)

**Reply by philfry9** [reply]
Thanks! Appreciate it.

**Reply by Schluggi** [reply, marked as answer]
Sorry for the delay. I've to wait for my S2 order. I just created a branch. At the moment not everything is tested. But you can try it by changing your config:

```yaml
packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: s2fixes  # <-- change this
    refresh: 1s   # <-- change this
```
