### ISSUE TITLE
PCB Release v3.0.0

### ISSUE THREAD

**Issue by Schluggi** [Schluggi/AIOsense#132]
We need a new PCB version for all the new components:

- LD2450 support (#92)
- Speaker (#74, #129)
- OLED Display (#126)

**Comment by jaws35smith** [comment]
@mourix I believe that the PCB silk screen has an error. The MAX98357 has the negative on the left side of the board closet to the LRC and DIN. The Silk screen prints the "+" on that side and positions the positive leads in the center of the board for the speaker This in turn can result in the incorrect installation of the speaker orientation. The PTH Pads seem to need to be reshaped and relabeled for the speaker and relabeled for the output of the MAX98357. 
![adafruit_products_3006_iso_ORIG](https://github.com/user-attachments/assets/1f15423a-80fe-4905-b649-58b321a780a4)
![KICAD_AIOSENSE](https://github.com/user-attachments/assets/5bb26956-44f7-478a-adda-502dbbecc0e5)

**Comment by s-gordon** [comment]
@mourix With the speaker orientation reversed per the comment from @jaws35smith I am seeing poor performance on 3013 speakers. Audio, if it comes through at all, is very crackly and unintelligible. On a breadboard using the same pins and configuration I am seeing great performance with Piper TTS.

I recall reading somewhere that MAX98357 likes wide output traces.

```yaml
substitutions:
  name: "aiosense-v3"  # lowercase only, have to be unique
  friendly_name: "AIOsense v3"  # device name and entity prefix

  i2s_lrclk_pin: "GPIO34" # WS
  i2s_bclk_pin: "GPIO36"  # SCK
  i2s_din_pin: "GPIO40"   # DA
  i2s_mic_din_pin: "GPIO38"   # DA

...

packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: pcb-3.0.0-rc1
    refresh: 1d
    files:
      - esphome/packages/config/base.yaml

      # ----- board -----
      - esphome/packages/config/esp32-s2-mini.yaml

...

i2s_audio:
  - id: i2s_audiobus
    i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
    i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_dout_pin: "${i2s_din_pin}"
    mode: mono
    id: media_out

...

esphome:
  min_version: 2024.06.0
```

**Comment by Schluggi** [comment]
Hi [s-gordon](https://github.com/s-gordon),

I was not able to reproduce this behavior. Sounds great so far. Maybe bad/cold solder points?


https://github.com/user-attachments/assets/8cea93e5-7803-4df8-93b0-f7598cf5278e

**Comment by AnthonyPluth** [comment]
@Schluggi do you have a working speaker config? I got everything else working but can't get anything to come out of the speaker

**Comment by s-gordon** [comment]
> Hi [s-gordon](https://github.com/s-gordon),
> 
> I was not able to reproduce this behavior. Sounds great so far. Maybe bad/cold solder points?
> 
>  PXL_20250202_110024974.mp4

Thanks for the follow up here. Quite possibly a bad solder joint. This is working nicely for me now. It was one or both of bad network rules and solder joints.

**Comment by s-gordon** [comment]
> [@Schluggi](https://github.com/Schluggi) do you have a working speaker config? I got everything else working but can't get anything to come out of the speaker

@AnthonyPluth This is my [working VA configuration](https://github.com/s-gordon/AIOsense/blob/voice_assistant/esphome/packages/sensors/voice_assistant-rgb_led.yaml) on the S3 mini with relevant snippets below for good measure. PSRAM is likely wanted.

The [media_player component](https://github.com/s-gordon/AIOsense/blob/voice_assistant/esphome/packages/sensors/media_player-psram.yaml) also works for me if using the Arduino framework. PSRAM is mandatory if using the S2 mini.

```
substitutions:
  i2s_lrclk_pin: GPIO34   # WS
  i2s_bclk_pin: GPIO38    # SCK
  i2s_din_pin: GPIO37     # mic
  i2s_dout_pin: GPIO33    # speaker

i2s_audio:
  id: i2s_audiobus
  i2s_lrclk_pin: "${i2s_lrclk_pin}"  # WS
  i2s_bclk_pin: "${i2s_bclk_pin}"  # SCK

microphone:
  - platform: i2s_audio
    id: external_microphone
    channel: left
    adc_type: external
    i2s_din_pin: "${i2s_din_pin}"  # SD
    i2s_audio_id: i2s_audiobus
    pdm: false

speaker:
  - platform: i2s_audiobus
    id: va_speaker
    i2s_dout_pin: ${i2s_dout_pin}
    dac_type: external
    channel: mono
```
