### ISSUE TITLE
Unable to see LD2410C data

### ISSUE THREAD

**Issue by silviudc** [Schluggi/AIOsense#328]
I have an odd issue or maybe a bad config? I have printed out the PCB for the S3 minis and I have the following sensors attached: BME680, GY-302 and the LD2410c
My LD2410c is being detected as a BT device and I can add it separately and seems to work but under the aiosensor esphome device it does not, any idea what I'm doing wrong?

See below for esphome yaml:

```
substitutions:
  name: "aiosense-bedroom"  # lowercase only, have to be unique
  friendly_name: "AIOsense Bedroom"  # device name and entity prefix
  bme_address: "0x77"

  # bh1750_update_interval: 5s

  # bme_address: "0x76"  # for some modules you have to change it to 0x77
  # bme_update_interval: 30s

  # co2_offset: "0"  # bsec only
  # humidity_offset: "0"
  # iaq_offset: "0" # bsec only
  # illuminance_offset: "0"
  # pressure_offset: "0"
  temperature_offset: "-6"
  # voc_offset: "0" # bsec only

  # LD2410(c) does not work? Please notice:
  # https://aiosense.readthedocs.io/en/latest/debugging/#ld2410c-does-not-work

  # pir_delayed_off: 1s
  # pir_delayed_on: 0s

  # led_strobe_on: 50ms   # controls the strobe effect if rgb_led or led is enabled
  # led_strobe_off: 100ms

packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: esphome-v3.0.1
    refresh: 1d
    files:
      - esphome/packages/config/base.yaml

      # ----- board -----
      # - esphome/packages/config/esp32-c3-mini.yaml
      # - esphome/packages/config/esp32-d1-mini.yaml
      # - esphome/packages/config/esp32-s2-mini.yaml
      - esphome/packages/config/esp32-s3-mini.yaml
      # - esphome/packages/config/esp8266-d1-mini.yaml

      # ----- modules -----
      - esphome/packages/sensors/bh1750.yaml
      # - esphome/packages/sensors/bme280.yaml  # enable for bme280
      # - esphome/packages/sensors/bme680.yaml  # disable for bme280
      - esphome/packages/sensors/bme68x_bsec.yaml  # disable for bme280      
      - esphome/packages/sensors/buzzer.yaml  # PCB >= v2.1.0
      - esphome/packages/sensors/occupancy.yaml  # only if pir & mmWave are activated
      - esphome/packages/sensors/pir.yaml

      # ----- voice assistant (use rgb_led for esp32-c3 & esp32-s3 only-----
      # - esphome/packages/sensors/voice_assistant-rgb_led.yaml
      # - esphome/packages/sensors/voice_assistant-led.yaml

      # ----- led modules (use rgb_led for esp32-c3 & esp32-s3 only) -----
      - esphome/packages/sensors/rgb_led.yaml
      # - esphome/packages/sensors/led.yaml
      # - esphome/packages/sensors/status_led.yaml

      # ----- mmWave radar sensor -----
      - esphome/packages/sensors/ld2410.yaml
      #- esphome/packages/sensors/sen0395.yaml

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger: 
```

I assume  https://aiosense.readthedocs.io/en/latest/debugging/#ld2410c-does-not-work doesn't help because the sensor is being detected by BT and works independently

![Image](https://github.com/user-attachments/assets/40f5f604-c045-4de0-8e94-4086af9ecda7)
