### ISSUE TITLE
PIR always stays in detected, never clears

### ISSUE THREAD

**Issue by silviudc** [Schluggi/AIOsense#344]
Cannot seem to get the PIR to work at all, I have tried 3 sensors and all stay stuck in detected:

![Image](https://github.com/user-attachments/assets/1a6dc80a-28e0-4089-8e14-a7ea4f6e5bf9)

![Image](https://github.com/user-attachments/assets/19252434-e00d-4bdc-87d8-73efeefdedc0)

I have confirmed with the multimeter that the 3 pins are correctly going to GND, 3v and GPIO11.
No idea what else to try.

Here is the esphome code:

```
substitutions:
  name: "dining-room"  # lowercase only, have to be unique
  friendly_name: "Dining Room"  # device name and entity prefix
  
  # ESP32-S2 mini
  uart_rx_pin: GPIO43 #ON
  uart_tx_pin: GPIO44 #ON
  bme_address: "0x77" #ON
  bh1750_update_interval: 5s
  bme_update_interval: 30s

  # co2_offset: "0"  # bsec only
  # humidity_offset: "0"
  # iaq_offset: "0" # bsec only
  # illuminance_offset: "0"
  # pressure_offset: "0"
  temperature_offset: "-6"
  # voc_offset: "0" # bsec only

  # LD2410(c) does not work? Please notice:
  # https://aiosense.readthedocs.io/en/latest/debugging/#ld2410c-does-not-work

  pir_delayed_off: 1s
  pir_delayed_on: 0s

  led_strobe_on: 50ms   # controls the strobe effect if rgb_led or led is enabled
  led_strobe_off: 100ms

packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: esphome-v3.0.1
    refresh: 1d
    files:
      - esphome/packages/config/base.yaml

      # ----- board -----
      # - esphome/packages/config/esp32-c3-mini.yaml
      # - esphome/packages/config/esp32-d1-mini.yaml
      # - esphome/packages/config/esp32-s2-mini.yaml
      - esphome/packages/config/esp32-s3-mini.yaml
      # - esphome/packages/config/esp8266-d1-mini.yaml

      # ----- modules -----
      - esphome/packages/sensors/bh1750.yaml 
      # - esphome/packages/sensors/bme280.yaml  # enable for bme280
      # - esphome/packages/sensors/bme680.yaml  # disable for bme280
      - esphome/packages/sensors/bme68x_bsec.yaml  # disable for bme280     
      #- esphome/packages/sensors/buzzer.yaml  # PCB >= v2.1.0
      - esphome/packages/sensors/occupancy.yaml  # only if pir & mmWave are activated 
      - esphome/packages/sensors/pir.yaml 

      # ----- voice assistant (use rgb_led for esp32-c3 & esp32-s3 only-----
      #- esphome/packages/sensors/voice_assistant-rgb_led.yaml
      # - esphome/packages/sensors/voice_assistant-led.yaml

      # ----- led modules (use rgb_led for esp32-c3 & esp32-s3 only) -----
      - esphome/packages/sensors/rgb_led.yaml
      # - esphome/packages/sensors/led.yaml
      # - esphome/packages/sensors/status_led.yaml

      # ----- mmWave radar sensor -----
      - esphome/packages/sensors/ld2410.yaml
      #- esphome/packages/sensors/sen0395.yaml

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "xxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
    
```
