### ISSUE TITLE
BME680 error

### ISSUE THREAD

**Issue by afp316** [Schluggi/AIOsense#60]
**Category**
- [ ] Hardware / PCB
- [x] Software / ESPHome

**Version of ESPHome / AIOsense**
ESPHome: 2023.3.2
AIOsense: latest

**Describe the bug**
I get an error with the bme680 initialization.  It wants me to append "_m" to several variables in the cpp file.  I searched to find this error but couldn't come up with anything.  I apologize if there is already a solution.  See the link for my logs.

[logs_aio-utility-room_run.txt](https://github.com/Schluggi/AIOsense/files/11107146/logs_aio-utility-room_run.txt)

**Comment by Schluggi** [comment]
Hi @afp316,

please share your YAML as well :)

**Comment by afp316** [comment]
oops crap, sorry about that.  noob moment.  Thanks for you patience..

[aio-utility-room.yaml.txt](https://github.com/Schluggi/AIOsense/files/11122228/aio-utility-room.yaml.txt)

I haven't included any pw's or keys in the txt.

**Comment by Schluggi** [comment]
Thank you @cadriel for the quick fix.

Unfortunately if you want to use bsec you have to downgrade your ESPHome. 

It should be possible to use the new bsec component @cadriel had linked, but it does not work for me now. We have to wait for a fix :/

**Comment by afp316** [comment]
Thank you @cadriel !  That did the trick for me.

**Comment by afp316** [comment]
signed off complete based on the @cadriel fix that works for me.

**Comment by CappyT** [comment]
Any updates on this? IAQ would be cool to have. The bsec2 lib should be there, I don't know what is blocking the functionality right now

Thanks

**Comment by Schluggi** [comment]
> Any updates on this? IAQ would be cool to have. The bsec2 lib should be there, I don't know what is blocking the functionality right now

Yes. This would be nice. The problem is Bosch uses a library called "BSEC" which calculates the IAQ value. BSEC1 is not compatible with any ESP32. Unfortunately is this the version in the current ESPHome version. 

Bosch released BSEC2 some time ago but no one has implemented this into ESPHome yet. Therefore is this (non working) [pull request](https://github.com/esphome/esphome/pull/4585).

There is also a time you could use [this modified fork](https://github.com/Schluggi/esphome/tree/bme68x_bsec) by @neffs to make it work (which uses bsec version 2). But ESPHome had a breaking change so this does not work anymore.

You could try using an ESP8266, since BSEC1 should work there or to downgrade ESPHome to (September 2022 (i think?)) and use my modified fork. But there is a chance other modules uses newer features that were not available at this time.

Since I can't code C++ that well, I'm unable to fix it myself. If you can... I would be happy :)

**Comment by florianmulatz** [comment]
Is there a way to include this one as temporary fix?

https://github.com/esphome/esphome/pull/4585

**Comment by Schluggi** [comment]
> Is there a way to include this one as temporary fix?
> 
> [esphome/esphome#4585](https://github.com/esphome/esphome/pull/4585)

You are fast.. but I'm as well ;)

Yes, I just created PR #122. But this PR has some breaking changes.
You can try out by editing your packages:

```yaml
packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: bsec_is_back # << changed from main
    refresh: 1d
    files:
      # [...] other files
      # - esphome/packages/sensors/bme280.yaml  # comment this line 
      # - esphome/packages/sensors/bme680.yaml  # comment this line 
      - esphome/packages/sensors/bme68x_bsec.yaml # add this line
      # [...] other files
```
Please notice the changed and removed substitutions:
`bmex80_address` -> `bme_address`
`bmex80_update_interval` -> `bme_update_interval`
`bme680_bsec_sample_rate` -> gone. not part of the quickfix
`bme680_bsec_temperature_offset` -> gone. not part of the quickfix
