### ISSUE TITLE
LD2410 Sensors "Unknown" Status

### ISSUE THREAD

**Issue by afp316** [Schluggi/AIOsense#97]
**Category**
- [ ] Hardware / PCB
- [X] Software / ESPHome

**Version of ESPHome / AIOsense**
ESPHome version 2023.7.0
Project Schluggi.AIOsense version 2.0.0

**AIOsense Configuration**
Lolin ESP32-C3 Mini
BME 680
BH1750
LD2410 mmWave
PIR
PCB V2.0-RC4 02/23

**Describe the bug**
Relates to PR #45.

Flashed the CPU with the appropriate config mods to my esp32-c3-mini.  See config below:

```
substitutions:
  name: "aio-garage"  # lowercase only, have to be unique
  friendly_name: "aio-garage"  # device name and entity prefix
  version: "2.0.0"  # your AIOsense version

  bh1750_update_interval: 5s

  bmex80_address: "0x77"  # for some modules you have to change it to 0x77
  # bmex80_offset_humidity: "0"
  # bmex80_offset_temperature: "0"
  # bmex80_update_interval: 30s

  # bme680_bsec_sample_rate: lp # lp -> 3s, ulp ->5min
  # bme680_bsec_temperature_offset: "0"

  ld2410_max_distance_move: 4.5m
  ld2410_max_distance_still: 4.5m
  ld2410_timeout: 5s

  pir_delayed_off: 1s
  pir_delayed_on: 0s

packages:
  remote_package:
    url: https://github.com/schluggi/AIOsense
    ref: main
    refresh: 1d
    files:
      - esphome/packages/config/base.yaml

      # --- select your board ---
      - esphome/packages/config/esp32-c3-mini.yaml
      # - esphome/packages/config/esp32-d1-mini.yaml
      # - esphome/packages/config/esp32-s2-mini.yaml
      # - esphome/packages/config/esp8266-d1-mini.yaml

      # --- select your sensors ---
      - esphome/packages/sensors/bh1750.yaml
      # - esphome/packages/sensors/buzzer.yaml  # AIOsense >= 2.1.x only
      # - esphome/packages/sensors/bme280.yaml  # enable for bme280
      - esphome/packages/sensors/bme680.yaml  # disable for bme280
      # - esphome/packages/sensors/bme680_bsec.yaml  # does not work yet
      - esphome/packages/sensors/occupancy.yaml  # only if pir & mmWave are on
      - esphome/packages/sensors/pir.yaml
      - esphome/packages/sensors/rgb_led.yaml  # esp32-c3-mini only
      # - esphome/packages/sensors/led.yaml  # d1-mini only

      # --- select your radar sensor ---
      - esphome/packages/sensors/ld2410.yaml
      #  - esphome/packages/sensors/sen0395.yaml


# Enable Home Assistant API
api:
  encryption:
    key: !secret aio_garage_api

ota:
  password: !secret aio_garage_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 192.168.1.111
  #   subnet: 255.255.255.0
  #   gateway: 192.168.1.1

# bluetooth_proxy:
```
Upload was successful.  All sensors worked except LD2410 as shown below with the "Unknown" status indicators:

![image](https://github.com/Schluggi/AIOsense/assets/96469846/078b6f84-008a-4866-8bdc-bf8761f0d07c)

**Recommended Solution**

Change the following uart config in packages/sensor/ld2410.yaml from this:
```
uart:
  # switching rx & tx is not a mistake but necessary
  tx_pin: "${uart_rx_pin}"
  rx_pin: "${uart_tx_pin}"
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
```
To this:
```
uart:
  # enable for all cpu's but esp32-c3-mini
  # rx_pin: "${uart_tx_pin}"
  # tx_pin: "${uart_rx_pin}"
  # enable for esp32-c3-mini
  rx_pin: "${uart_rx_pin}"
  tx_pin: "${uart_tx_pin}"
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
```
Result:
![image](https://github.com/Schluggi/AIOsense/assets/96469846/46e62d10-f13e-4316-b93d-2008b770f6e1)

***My disclaimer is that I don't have any of the other cpu's so I can not confirm when you must swap the uart pins to enable coms with the LD2410.  This does work with the esp32-c3-mini though.***
